### ISSUE TITLE
GCL wake cut out prematurely?

### ISSUE THREAD

**Issue by rethore** [DTUWindEnergy/FUSED-Wake#5]
Requests from Bryce Ingersoll:

> I am working with Jared Thomas and Dr. Ning at Brigham Young University on a project comparing wind turbine wake models for optimization. We are investigating the differences in results when various wake models, including the Larsen model, are used with gradient-based optimization. We are seeing a discontinuity in the wake calculations, and are hoping you can point us in the right direction.
> 
> A simple wind farm layout was set up which includes two wind turbines. We calculated the power output of the two wind turbines, where one wind turbine is in the wake of the upstream wind turbine. The upstream wind turbine's power output remains constant, while the power output of the downstream wind turbine changes as we move its position across the wake of the upstream turbine.
> 
> When the power output for the downstream turbine is calculated, it appears that the wake effect is prematurely cutoff, resulting in the discontinuities shown in the included figure. This discontinuity occurs before the wake radius. Is this supposed to occur? Also, if it isn't supposed to happen, have you seen something similar occur before? At what position the discontinuity occurs appears to depend heavily on the ambient turbulence intensity, and the discontinuity's magnitude appears to be influenced by the thrust coefficient.
> 
> The included plot uses the following parameters:
> TI = 0.05 
> wind speed = 8 m/s
> wind direction = 240 deg
> air density = 1.1716 kg/m^3
> rotor diameter = 126.4 m
> hub height = 90 m
> The downstream turbine is 7 diameters behind the upstream turbine.
> 
> We are using gcl.py from https://github.com/DTUWindEnergy/FUSED-Wake/tree/master/fusedwake/gcl/python
> 
> Any suggestions would be greatly appreciated.

![0](https://cloud.githubusercontent.com/assets/2746159/15567099/ad7d99de-2324-11e6-98fd-e591a459cbec.png)

**Comment by rethore** [comment]
Right now it's cut at the calculated wake width Rw, and cut a line [L276](https://github.com/DTUWindEnergy/FUSED-Wake/blob/master/fusedwake/gcl/python/gcl.py#L276). It seems a bit dramatic on the plot provided, so I guess the cutout could be done later. I can't recall why the cutout was needed in the first place, it might be something that was done to reduce the number of function calls of get_dU. In the present implementation it doesn't seem to be the case, so maybe it can be safely removed. What do you think @jp5000?

**Comment by jp5000** [comment]
The variable Rw controls the location of the discontinuity. In the original paper the Rw is used to define the wake width and the expression given in [L185] is the result of the asymptotic self-similar solution of the  axis-symmetric thin shear layer approximation of Navier-Stokes. It is a good question to ask ourselves if it is necessary to make the discontinuity exactly at Rw or if we could remove the restriction of [L276](https://github.com/DTUWindEnergy/FUSED-Wake/blob/master/fusedwake/gcl/python/gcl.py#L276). I will run some test cases and come back to you.

**Comment by jp5000** [comment]
Thank you Bryce Ingersoll. There was a bug in the GCLarsen function [L462](https://github.com/DTUWindEnergy/FUSED-Wake/blob/master/fusedwake/gcl/python/gcl.py#L462) inside gcl.py (i.e. py_gcl_v1 in FusedWake). The extreme wake used to precompute which turbines are under wake was causing this early deficit truncation. This problem is fixed in the new version of GCL.
